# Generated by Django 5.0.14 on 2026-06-10 05:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_fee_rate', models.DecimalField(decimal_places=2, default=7.5, help_text='Success fee percentage (e.g. 7.5 for 7.5%)', max_digits=5)),
                ('success_fee_cap', models.DecimalField(decimal_places=2, default=75.0, help_text='Maximum fee cap per job (e.g. 75.00 for FJD $75)', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(upload_to='sponsors/')),
                ('destination_url', models.URLField()),
                ('placement', models.CharField(choices=[('homepage', 'Homepage'), ('browse_tasks_sidebar', 'Browse Tasks Sidebar'), ('task_detail_sidebar', 'Task Detail Sidebar'), ('client_dashboard', 'Client Dashboard'), ('tradie_dashboard', 'Tradie Dashboard'), ('how_it_works', 'How It Works')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sponsor / Ad Banner',
                'verbose_name_plural': 'Sponsors / Ad Banners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Trade Category',
                'verbose_name_plural': 'Trade Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='publicreview',
            name='timeline_score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='quote',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='client_quote_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='earliest_available_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='estimated_job_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='estimated_platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='estimated_tradie_take_home',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='include_platform_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='includes_materials',
            field=models.BooleanField(default=False, verbose_name='Includes materials'),
        ),
        migrations.AddField(
            model_name='quote',
            name='platform_fee_cap_at_quote_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='platform_fee_rate_at_quote_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='warranty_or_followup_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='access_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='budget_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed price'), ('flexible', 'Flexible'), ('quote_needed', 'Quote needed')], max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='final_job_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='materials_required',
            field=models.CharField(blank=True, choices=[('client_supplies', 'Client supplies materials'), ('tradie_supplies', 'Tradie supplies materials'), ('not_sure', 'Not sure')], max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='parking_available',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not sure')], max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='urgency',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('this_week', 'This week'), ('flexible', 'Flexible')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('plumbing', '🔧 Plumbing'), ('electrical', '⚡ Electrical'), ('cleaning', '🧹 Cleaning'), ('gardening', '🌿 Gardening'), ('carpentry', '🪚 Carpentry'), ('painting', '🎨 Painting'), ('aircon', '❄️ Air Conditioning'), ('removalist', '🚛 Removalist'), ('building', '🏗️ Building'), ('locksmith', '🔒 Locksmith'), ('it', '🖥️ IT / Tech'), ('pest', '🐛 Pest Control'), ('other', '🔨 Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tradie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_job_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee_cap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('waived', 'Waived'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_fees', to='marketplace.task')),
                ('tradie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Fee',
                'verbose_name_plural': 'Platform Fees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='marketplace.invoice')),
                ('platform_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.platformfee')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaskPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marketplace.task')),
            ],
            options={
                'verbose_name': 'Task Photo',
                'verbose_name_plural': 'Task Photos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='marketplace.tradecategory'),
        ),
    ]
