# Generated by Django 5.0.14 on 2026-06-10 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_platformsettings_sponsor_tradecategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradecategory',
            options={'ordering': ['name'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='tradecategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='marketplace.tradecategory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('plumbing', '🔧 Plumbing'), ('electrical', '⚡ Electrical'), ('cleaning', '🧹 Cleaning'), ('gardening', '🌿 Gardening'), ('carpentry', '🪚 Carpentry'), ('painting', '🎨 Painting'), ('aircon', '❄️ Air Conditioning'), ('removalist', '🚛 Removalist'), ('building', '🏗️ Building'), ('locksmith', '🔒 Locksmith'), ('it', '🖥️ IT / Tech'), ('pest', '🐛 Pest Control'), ('other', '🔨 Other'), ('chef', '🍳 Chef'), ('baker', '🥐 Baker'), ('mechanic', '🛠️ Mechanic'), ('photographer', '📸 Photographer'), ('makeup', '💄 Makeup Artist')], max_length=20),
        ),
    ]
