# Generated by Django 5.0.14 on 2026-06-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_public_review_criteria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicreview',
            options={'verbose_name': 'Public Review (Client → Provider)', 'verbose_name_plural': 'Public Reviews (Client → Provider)'},
        ),
    ]
