# Generated by Django 5.0.14 on 2026-06-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_publicreview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='large_job_fee_rate',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Fee percentage for large jobs over threshold', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='large_job_threshold',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Customer-facing quote threshold for large job fee rate (e.g. 5000.00)', max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_facing_quote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='estimated_provider_take_home',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='fee_rule_applied',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='large_job_fee_rate_at_quote_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='large_job_threshold_at_quote_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='minimum_take_home_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='success_fee_cap_at_quote_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='success_fee_rate_at_quote_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
