# Generated by Django 5.0.14 on 2026-06-10 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_platformsettings_large_job_fee_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_includes',
            field=models.CharField(blank=True, choices=[('labour_only', 'Labour only'), ('labour_and_materials', 'Labour and materials'), ('materials_to_be_confirmed_after_inspection', 'Materials to be confirmed after inspection'), ('service_only', 'Service only'), ('service_plus_products', 'Service plus products/supplies'), ('not_applicable', 'Not applicable')], max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='after_hours_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='backdoor_monitoring_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='backdoor_monitoring_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='backdoor_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='backdoor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='backdoor_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backdoor_reviewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='clean_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='client_provide_photos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='delivery_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='materials_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='materials_responsibility',
            field=models.CharField(blank=True, choices=[('client_will_supply', 'Client will supply materials'), ('provider_should_supply', 'Provider should supply materials'), ('provider_to_advise_after_inspection', 'Provider should advise after inspection'), ('not_applicable', 'Not applicable'), ('not_sure', 'Not sure')], max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='meals_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='on_site_inspection_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='parking_available_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='parking_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='removal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='rubbish_removal_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='site_access_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tools_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='warranty_followup_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QuotingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_quoting_appointments', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_quoting_appointments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoting_appointments', to='marketplace.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotingAppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quoting_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='marketplace.quotingappointment')),
            ],
            options={
                'ordering': ['proposed_date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='quotingappointment',
            name='selected_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='marketplace.quotingappointmentslot'),
        ),
    ]
