# Generated by Django 5.0.14 on 2026-06-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_invoice_period_end_invoice_period_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradieprofile',
            name='business_licence',
            field=models.FileField(blank=True, upload_to='provider_documents/', verbose_name='Business Licence'),
        ),
        migrations.AddField(
            model_name='tradieprofile',
            name='documents_verified',
            field=models.BooleanField(default=False, verbose_name='Documents verified by admin'),
        ),
        migrations.AddField(
            model_name='tradieprofile',
            name='electrical_contractors_licence',
            field=models.FileField(blank=True, upload_to='provider_documents/', verbose_name='Electrical Contractors Licence'),
        ),
        migrations.AddField(
            model_name='tradieprofile',
            name='plumber_licence',
            field=models.FileField(blank=True, upload_to='provider_documents/', verbose_name='Plumber Licence'),
        ),
        migrations.AddField(
            model_name='tradieprofile',
            name='public_liability_insurance',
            field=models.FileField(blank=True, upload_to='provider_documents/', verbose_name='Public Liability Insurance'),
        ),
        migrations.AddField(
            model_name='tradieprofile',
            name='tin_letter',
            field=models.FileField(blank=True, upload_to='provider_documents/', verbose_name='TIN Letter'),
        ),
        migrations.AlterField(
            model_name='tradieprofile',
            name='tin',
            field=models.CharField(blank=True, max_length=50, verbose_name='TIN Number (optional)'),
        ),
    ]
