# Generated by Django 5.0.14 on 2026-06-18 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_tradieprofile_business_licence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(blank=True, choices=[('platform_fee', 'Platform Fee'), ('platform_circumvention_fee', 'Platform Circumvention Fee'), ('adjustment', 'Adjustment'), ('recovery_cost', 'Recovery Cost')], default='platform_fee', max_length=30),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='terms_version',
            field=models.CharField(default='1.0', help_text='Active terms version presented to users at registration', max_length=20),
        ),
        migrations.AddField(
            model_name='tradieprofile',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Verification notes (admin only)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='backdoor_monitoring_flag',
            field=models.BooleanField(default=False, verbose_name='Platform Circumvention Flag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='backdoor_monitoring_note',
            field=models.TextField(blank=True, verbose_name='Platform Circumvention Note'),
        ),
        migrations.AlterField(
            model_name='task',
            name='backdoor_reviewed',
            field=models.BooleanField(default=False, verbose_name='Circumvention Reviewed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='backdoor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Circumvention Reviewed At'),
        ),
        migrations.AlterField(
            model_name='task',
            name='backdoor_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backdoor_reviewed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Circumvention Reviewed By'),
        ),
        migrations.CreateModel(
            name='PlatformCircumventionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_job_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('client_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('waived', 'Waived'), ('disputed', 'Disputed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('evidence_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circumvention_cases_as_client', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circumvention_cases_as_provider', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circumvention_cases_reviewed', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circumvention_cases', to='marketplace.task')),
            ],
            options={
                'verbose_name': 'Platform Circumvention Case',
                'verbose_name_plural': 'Platform Circumvention Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('invoice', 'Invoice Notice'), ('payment_reminder', 'Payment Reminder'), ('circumvention', 'Platform Circumvention Notice'), ('terms_update', 'Terms Update Notice'), ('general', 'General Notice')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_platform', 'In-Platform'), ('sms', 'SMS')], default='email', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_notices', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Notice',
                'verbose_name_plural': 'Platform Notices',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accepted_platform_circumvention', models.BooleanField(default=False, verbose_name='Accepted Platform Circumvention Fee policy')),
                ('accepted_invoicing_terms', models.BooleanField(default=False, verbose_name='Accepted invoicing / payment obligations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms Acceptance',
                'verbose_name_plural': 'Terms Acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
