# Generated by Django 5.0.14 on 2026-07-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_tradieprofile_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformnotice',
            name='notice_type',
            field=models.CharField(choices=[('welcome', 'Welcome Message'), ('invoice', 'Invoice Notice'), ('payment_reminder', 'Payment Reminder'), ('circumvention', 'Platform Circumvention Notice'), ('terms_update', 'Terms Update Notice'), ('general', 'General Notice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='materials_responsibility',
            field=models.CharField(blank=True, choices=[('client_will_supply', 'Client will supply materials'), ('provider_should_supply', 'Local pro should supply materials'), ('provider_to_advise_after_inspection', 'Local pro should advise after inspection'), ('not_applicable', 'Not applicable'), ('not_sure', 'Not sure')], max_length=50),
        ),
    ]
