# Generated by Django 5.0.14 on 2026-07-11 04:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_remove_sponsor_placement_sponsor_placements'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed amount off (FJD)'), ('percent', 'Percentage off')], default='fixed', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Dollar amount, or percentage if "Percentage off" is selected.', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, help_text='Leave blank for no start restriction.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for no end restriction.', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='platformfee',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='platformfee',
            name='gross_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='estimated_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='used_founding_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradieprofile',
            name='founding_member_credit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Founding member credit balance (FJD)'),
        ),
        migrations.AddField(
            model_name='tradieprofile',
            name='is_founding_member',
            field=models.BooleanField(default=False, verbose_name='Founding member'),
        ),
        migrations.AddField(
            model_name='quote',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='marketplace.promocode'),
        ),
    ]
