# Generated by Django 5.0.14 on 2026-07-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_promocode_platformfee_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='materials_responsibility',
            field=models.CharField(blank=True, choices=[('client_will_supply', 'Client will supply materials'), ('provider_should_supply', 'Local professional should supply materials'), ('provider_to_advise_after_inspection', 'Local professional should advise after inspection'), ('not_applicable', 'Not applicable'), ('not_sure', 'Not sure')], max_length=50),
        ),
    ]
