# Generated by Django 5.0.14 on 2026-07-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_baker_cake_icon_seed_nanny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformfee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('waived', 'Waived'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='town',
            field=models.CharField(choices=[('Suva', 'Suva'), ('Nadi', 'Nadi'), ('Lautoka', 'Lautoka'), ('Nausori', 'Nausori'), ('Labasa', 'Labasa')], db_index=True, max_length=50),
        ),
    ]
