# Generated by Django 5.0.14 on 2026-07-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_alter_platformfee_status_alter_quote_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_email_new_job_match',
            field=models.BooleanField(default=False, verbose_name='Email me when a new job matching my trades and towns is posted'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email_new_message',
            field=models.BooleanField(default=True, verbose_name='Email me when I receive a new message'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email_new_quote',
            field=models.BooleanField(default=True, verbose_name='Email me when a local professional quotes on my job'),
        ),
        migrations.AlterField(
            model_name='platformnotice',
            name='notice_type',
            field=models.CharField(choices=[('welcome', 'Welcome Message'), ('invoice', 'Invoice Notice'), ('payment_reminder', 'Payment Reminder'), ('circumvention', 'Platform Circumvention Notice'), ('terms_update', 'Terms Update Notice'), ('general', 'General Notice'), ('new_quote', 'New Quote Received'), ('new_message', 'New Message'), ('new_job_match', 'New Job Match')], max_length=30),
        ),
    ]
