# Generated by Django 5.0.14 on 2026-07-22 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_user_notify_email_new_job_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_email_market_order_update',
            field=models.BooleanField(default=True, verbose_name='Email me when my Market order is accepted or declined'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email_new_market_order',
            field=models.BooleanField(default=True, verbose_name='Email me when someone orders from my Market listing'),
        ),
        migrations.AlterField(
            model_name='platformnotice',
            name='notice_type',
            field=models.CharField(choices=[('welcome', 'Welcome Message'), ('invoice', 'Invoice Notice'), ('payment_reminder', 'Payment Reminder'), ('circumvention', 'Platform Circumvention Notice'), ('terms_update', 'Terms Update Notice'), ('general', 'General Notice'), ('new_quote', 'New Quote Received'), ('new_message', 'New Message'), ('new_job_match', 'New Job Match'), ('new_market_order', 'New Market Order'), ('market_order_update', 'Market Order Update')], max_length=30),
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='market_listings/%Y/%m/%d/')),
                ('vat_applicable', models.BooleanField(default=False, verbose_name='VAT applicable')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VAT rate (%)')),
                ('take_home_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Take-home per unit (FJD)')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Buyer price per unit (FJD)')),
                ('fee_rate_at_listing', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Platform fee rate used (%)')),
                ('units_available', models.PositiveIntegerField()),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('fulfillment_method', models.CharField(choices=[('pickup', 'Pickup only'), ('delivery', 'Delivery only'), ('both', 'Pickup or delivery')], default='pickup', max_length=10)),
                ('pickup_town', models.CharField(blank=True, choices=[('Suva', 'Suva'), ('Nadi', 'Nadi'), ('Lautoka', 'Lautoka'), ('Nausori', 'Nausori'), ('Labasa', 'Labasa')], max_length=50)),
                ('delivery_towns', models.JSONField(blank=True, default=list)),
                ('order_mode', models.CharField(choices=[('auto', 'Auto-accept orders'), ('approval', 'Require my approval')], default='approval', max_length=10)),
                ('available_dates', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_listings', to='marketplace.tradecategory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market Listing',
                'verbose_name_plural': 'Market Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fulfillment_method', models.CharField(choices=[('pickup', 'Pickup only'), ('delivery', 'Delivery only'), ('both', 'Pickup or delivery')], max_length=10)),
                ('delivery_town', models.CharField(blank=True, choices=[('Suva', 'Suva'), ('Nadi', 'Nadi'), ('Lautoka', 'Lautoka'), ('Nausori', 'Nausori'), ('Labasa', 'Labasa')], max_length=50)),
                ('requested_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], db_index=True, default='pending', max_length=10)),
                ('fee_status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('waived', 'Waived')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_orders', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.marketlisting')),
            ],
            options={
                'verbose_name': 'Market Order',
                'verbose_name_plural': 'Market Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
