# Generated by Django 5.0.14 on 2026-07-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_user_notify_email_market_order_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlisting',
            name='food_type',
            field=models.CharField(blank=True, choices=[('cooked', 'Cooked'), ('premade', 'Premade (uncooked)'), ('produce', 'Produce')], max_length=20, verbose_name='Food type (if category is Food)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='vat_applicable',
            field=models.BooleanField(default=False, verbose_name='VAT applicable'),
        ),
        migrations.AddField(
            model_name='quote',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VAT rate (%)'),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='category',
            field=models.CharField(choices=[('food', '🍽️ Food'), ('clothes_toys', '🧸 Clothes & Toys'), ('furniture', '🪑 Furniture'), ('tools_parts', '🔧 Tools & Spare Parts'), ('other', '📦 Other')], db_index=True, default='other', max_length=20),
            preserve_default=False,
        ),
    ]
