# Generated by Django 5.0.14 on 2026-07-22 23:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_marketlisting_food_type_quote_vat_applicable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlisting',
            name='use_founding_credit',
            field=models.BooleanField(default=False, verbose_name='Apply founding seller credit to platform fees on this listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_market_founding_member',
            field=models.BooleanField(default=False, verbose_name='Market founding seller'),
        ),
        migrations.AddField(
            model_name='user',
            name='market_founding_credit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Market founding seller credit balance (FJD)'),
        ),
    ]
