# Generated by Django 5.0.14 on 2026-07-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_seed_tutor_swim_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformnotice',
            name='notice_type',
            field=models.CharField(choices=[('welcome', 'Welcome Message'), ('invoice', 'Invoice Notice'), ('payment_reminder', 'Payment Reminder'), ('circumvention', 'Platform Circumvention Notice'), ('terms_update', 'Terms Update Notice'), ('general', 'General Notice'), ('new_quote', 'New Quote Received'), ('new_message', 'New Message'), ('new_job_match', 'New Job Match'), ('new_market_order', 'New Market Order'), ('market_order_update', 'Market Order Update'), ('account_migrated', 'Account Migrated to Local Professional')], max_length=30),
        ),
    ]
