# Generated by Django 5.0.14 on 2026-07-23 04:03

from django.db import migrations, models


def backfill_already_approved(apps, schema_editor):
    """
    Electrical/Plumbing licence documents were required at registration
    before this change, so any profile already fully approved was already
    reviewed under the old process — grandfather them in as reviewed rather
    than retroactively blocking currently-active tradies from bidding.
    Profiles still pending/rejected/suspended are left unreviewed, matching
    the new policy that safety documents need an explicit review.
    """
    TradieProfile = apps.get_model('marketplace', 'TradieProfile')
    TradieProfile.objects.filter(verification_status='approved').update(safety_documents_reviewed=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_alter_platformnotice_notice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradieprofile',
            name='safety_documents_reviewed',
            field=models.BooleanField(default=False, verbose_name='Safety documents reviewed (Electrical/Plumbing licence)'),
        ),
        migrations.RunPython(backfill_already_approved, noop_reverse),
    ]
