# Generated by Django 5.0.14 on 2026-07-24 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_seed_more_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicreview',
            name='admin_note',
            field=models.CharField(blank=True, help_text='e.g. "Renovated my kitchen, 2024" — for a review added without a platform job.', max_length=200, verbose_name='Context (shown publicly in place of a job title when no task is linked)'),
        ),
        migrations.AlterField(
            model_name='publicreview',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_reviews', to='marketplace.task'),
        ),
    ]
